# Generated by Django 4.2.30 on 2026-07-12 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomReportAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modules', models.JSONField()),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('export_format', models.CharField(max_length=10)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('departments', models.ManyToManyField(to='core.department')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
