# Generated by Django 4.2.30 on 2026-07-12 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonEmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emission_source', models.CharField(max_length=200)),
                ('activity_value', models.DecimalField(decimal_places=4, max_digits=14)),
                ('co2e_value', models.DecimalField(decimal_places=4, editable=False, max_digits=14)),
                ('auto_recalculate', models.BooleanField(default=True)),
                ('reporting_period', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('unit', models.CharField(max_length=50)),
                ('coefficient', models.DecimalField(decimal_places=6, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SustainabilityGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('target_metric', models.CharField(max_length=150)),
                ('target_value', models.DecimalField(decimal_places=4, max_digits=14)),
                ('current_value', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('unit', models.CharField(max_length=50)),
                ('deadline', models.DateField()),
                ('scope', models.CharField(choices=[('org', 'Organization-wide'), ('dept', 'Department-specific')], max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('overdue', 'Overdue'), ('completed', 'Completed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department')),
            ],
        ),
        migrations.AddConstraint(
            model_name='emissionfactor',
            constraint=models.CheckConstraint(check=models.Q(('coefficient__gt', 0)), name='emission_factor_positive'),
        ),
        migrations.AddField(
            model_name='carbonemission',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emissions', to='core.department'),
        ),
        migrations.AddField(
            model_name='carbonemission',
            name='emission_factor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emissions', to='environmental.emissionfactor'),
        ),
    ]
