# Generated by Django 4.2.30 on 2026-07-12 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentESGScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environmental_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('social_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('governance_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('overall_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('last_calculated_at', models.DateTimeField(auto_now=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='esg_score', to='core.department')),
            ],
        ),
    ]
